### ISSUE TITLE
Sistemare il social sharing preview su Facebook e Telegram di OR

### ISSUE THREAD

**Issue by fpietrosanti** [decidiamo/openrousseau-website#2]
Il sito decidiamo.it fa una preview su Social FB e chat TG ordinato:
<img width="370" alt="Screenshot 2020-09-25 at 12 02 12" src="https://user-images.githubusercontent.com/770363/94254410-07546400-ff27-11ea-8abe-80b21fe8dc93.png">

<img width="448" alt="Screenshot 2020-09-25 at 12 00 52" src="https://user-images.githubusercontent.com/770363/94254420-0a4f5480-ff27-11ea-93c7-01722f1c97f6.png">

Mentre il sito openrousseau richiede fixing della FB Preview e della TG preview:
<img width="448" alt="Screenshot 2020-09-25 at 11 58 44" src="https://user-images.githubusercontent.com/770363/94254454-1804da00-ff27-11ea-8257-c5e2903fcaf9.png">

<img width="236" alt="Screenshot 2020-09-25 at 12 02 08" src="https://user-images.githubusercontent.com/770363/94254474-1e935180-ff27-11ea-9e0d-2289f2837307.png">

**Comment by puria** [comment]
Fixed in 0f328007cb2b1bf8489b5deec06271d0a6ef315e
